scalar Upload

# inputs
input CreateWorkspaceInput {
  name: String
  title: String
  customMessage: String
  workspaceQuestions: [WorkspaceQuestionInput]
  logoFile: Upload
  logoUrl: String
}

input WorkspaceQuestionInput {
  question: String
  type: String
  index: Int
  isMandatory: Boolean
  isRequired: Boolean
}

# types
type Workspace {
  id: String
  name: String
  title: String
  customMessage: String
  logoUrl: String
  workspaceQuestions: [WorkspaceQuestion]
  accessUrl: String
}

type WorkspaceQuestion {
  id: String
  question: String
  type: String
  index: Int
  isMandatory: Boolean
  isRequired: Boolean
}

# mutations
type Mutation {
  createWorkspace(workspaceInput: CreateWorkspaceInput): Workspace
}

# queries
type Query {
  getAllWorkspaces(name: String): [Workspace]
  getAWorkspace(id: String): Workspace
}
