scalar Upload

# inputs
input SubmitFeedbackFormInput {
  accessUrl: String
  questionResponses: [CreateQuestionResponseInput]
  attachments: [Upload]
}

input CreateQuestionResponseInput {
  questionId: String
  answer: String
}

input GetFeedbackResponsesInput {
  workspaceId: String
  inboxType: String
}

# types
type Feedback {
  id: String
  QuestionResponse: [QuestionResponse]
  UserAttachment: [UserAttachment]
}

type QuestionResponse {
  id: String
  answer: String
  workspaceQuestions: [WorkspaceQuestion]
}

# queries
type Query {
  getFeedbackForm(accessUrl: String): Workspace
  getFeedbackResponses(getFeedbackInput: GetFeedbackResponsesInput): [Feedback]
}

# mutations
type Mutation {
  submitFeedbackForm(feedbackInput: SubmitFeedbackFormInput): Boolean
}
