export const ENV_VARS = {
  DATABASE_URL: 'DATABASE_URL',
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  JWT_SECRET: 'JWT_SECRET',
  SALT_ROUNDS: 'SALT_ROUNDS',
  CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',
  CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  CLOUDINARY_CLOUD_NAME: 'CLOUDINARY_CLOUD_NAME',
};
